### ISSUE TITLE
Release for linux?

### ISSUE THREAD

**Issue by itsAudioo** [LordFetznschaedl/CS2InstantDefuse#1]
Is it possible to make a release for linux?

**Comment by LordFetznschaedl** [comment]
Latest release: https://github.com/LordFetznschaedl/CS2InstantDefuse/releases/latest

Be aware that changes to the servers happened last night and I need to validate that the plugin still works with the newest update. This will happen later today.
As soon as I have further updates I will post them in this Issue.

**Comment by LordFetznschaedl** [comment]
Latest release works for Linux

**Comment by itsAudioo** [comment]
I tested the plugin yesterday did not work, also some of my meta mod plugins cant load if i load counterstrike sharp, is there any way around it?

**Comment by LordFetznschaedl** [comment]
Did you update CounterStrikeSharp to the latest version?

Did you verify your Metamod Source installation? meta version

Did you update the gameinfo.gi again after the last update from valve?

Did you verify that CounterStrikeSharp is seen as a plugin by metamod? meta list

**Comment by itsAudioo** [comment]
I have newest metamod ver, counterstriek sharp is loaded when i do meta list, but my other plugins dont load becouse of cssharp, is there any other way to run your plugin?

**Comment by LordFetznschaedl** [comment]
I can't really tell you anything else. I have verified it on my Linux server and it worked without issues.

The only thing that comes to mind is that you are missing some libraries on your server. Those libraries are mentioned in the installation guide under https://docs.cssharp.dev/guides/getting-started/.

**Comment by itsAudioo** [comment]
tested today, it works fine, thanks

**Comment by LordFetznschaedl** [comment]
Did you find out what the issue was?

**Comment by itsAudioo** [comment]
I just deleted css.vdf from metamod, and load it manually after my plugin loads
