### ISSUE TITLE
Instant defuse breaks on never css versions

### ISSUE THREAD

**Issue by itsAudioo** [LordFetznschaedl/CS2InstantDefuse#5]
running css v52 and instan defuse dosent work

**Comment by LordFetznschaedl** [comment]
Hello @audiomaster99, 
Thank you for your message.
I will be taking a look at this as soon as possible.

**Comment by itsAudioo** [comment]
> Hello @audiomaster99, Thank you for your message. I will be taking a look at this as soon as possible.

Ok so the issue seems to be resolved on its own after a few server restarts
